### ISSUE TITLE
Not displaying the events in application 

### ISSUE THREAD

**Issue by GayatriMunde** [lohanidamodar/flutter_calendar#4]
The data related to event is getting stored in the firestore but it is not displaying anything in the application.

**Comment by cavedweller** [comment]
Same problem that I'm facing, code works perfectly until the stream builder. The streamList() does not return any data from the database, but when i run FirebaseFirestore.instance.collection('event').snapshots() and changing the StreamBuilder<QuerySnapshot> it returns an instance of the database but does not display data on screen. Please could you assist as to why the streamList() does not return data

**Comment by lohanidamodar** [comment]
@GayatriMunde @cavedweller 
Please first try to build the code in this repository, if it works, then compare it with your codebase regarding what you did differently.

If you wan't my help, paste your code and output in your debug console so that I might assist further.

**Comment by cavedweller** [comment]
I tried running your code but it keeps throwing an error on my side regarding The argument type EventModel can't be assigned to the parameter type 'EventModel 

The code below is my attempt, sorry in advance for any spaghetti code, i am new to this and to github so i dont quite know how to upload code properly

### **This is my provider class**
pretty much a copy and paste of your code excluding the title part 
import 'package:flutter/foundation.dart';

class EventUpload with ChangeNotifier {
  final String id;
  final String description;
  final DateTime eventDate;

  EventUpload({
    this.id,
    this.description,
    this.eventDate,
  });

  factory EventUpload.fromMap(Map data) {
    return EventUpload(
      description: data['description'],
      eventDate: data['event_date'],
    );
  }

  factory EventUpload.fromDS(String id, Map<String, dynamic> data) {
    return EventUpload(
      id: id,
      description: data['description'],
      eventDate: data['event_date'].toDate(),
    );
  }

  Map<String, dynamic> toMap() {
    return {
      "description": description,
      "event_date": eventDate,
      "id": id,
    };
  }
}

**### Below is my add event code**
this section does work, as it does upload the information to firebase 


 onPressed: () async {
                      if (_formKey.currentState.validate()) {
                       
                        setState(() {
                          processing = true;
                        });
                      
                        if (widget.note != null) {
                          await eventDBS.updateData(widget.note.id, {
                         
                            "description": _description.text,
                            "event_date": widget.note.eventDate
                          });
                        } else {
                          
                          await eventDBS.createItem(EventUpload(
                            
                              description: _description.text,
                              eventDate: uploadDaySelected()));
                        }
                        _description.clear();
                        Navigator.pop(context);
                        setState(() {
                          processing = false;
                        });
                      }
                    },

**### Below is the calendar itself**


import 'package:SocialApp/Res/Firestore.dart';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart'; //date format
import 'package:table_calendar/table_calendar.dart';
import './events.dart';
import '../Providers/Event_list.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';

class Calendar extends StatefulWidget {
  @override
  CalendarState createState() => CalendarState();
}

class CalendarState extends State<Calendar> {
  TextEditingController _eventController;
  DateTime selectedDate;
  
  Map<DateTime, List<dynamic>> _events;
  List<dynamic> _selectedEvents;
  CalendarController _controller;

  @override
  void initState() {
    super.initState();
    Firebase.initializeApp();
    _controller = CalendarController();
    _eventController = TextEditingController();
    _events = {};
    _selectedEvents = [];
  }

  Map<DateTime, List<dynamic>> _groupEvents(List<EventUpload> allEvents) {
    Map<DateTime, List<dynamic>> data = {};
    allEvents.forEach((event) {
      DateTime date = DateTime(
          event.eventDate.year, event.eventDate.month, event.eventDate.day, 12);
      if (data[date] == null) data[date] = [];
      print('group');
      print(event);
      data[date].add(event);
    });
    return data;
  }

  List<DocumentSnapshot> templist;
  @override
  Widget build(BuildContext context) {

    final devicesize = MediaQuery.of(context).size;
    double _width = devicesize.width;
    double _height = devicesize.height;
    return Container(
      color: Colors.black,
      child: SafeArea(
        child: Scaffold(
          body: Builder(
            builder: (context) {
              return StreamBuilder<List<EventUpload>>(
                stream: eventDBS.streamList(),
                builder: (context, snapshot) {
                  if (snapshot.hasData) {

                    print('has dataaaaaaaaaaaaaaaaa');
                    List<EventUpload> allEvents = snapshot.data;              
                    print(allEvents);

                    if (allEvents.isNotEmpty) {
                      print('called snapshot');
                      _events = _groupEvents(allEvents);
                    }
                  } else {
                    print('else statement - no data retrieved');

                    _events = {};
                    _selectedEvents = [];
                  }

**### lastly the debug console** 
Restarted application in 2 450ms.
D/ConnectivityManager(17377): unregisterNetworkCallback; CallingUid : 10225, CallingPid : 17377
D/ConnectivityManager(17377): unregisterNetworkCallback; CallingUid : 10225, CallingPid : 17377
D/ConnectivityManager(17377): requestNetwork; CallingUid : 10225, CallingPid : 17377
W/DynamiteModule(17377): Local module descriptor class for providerinstaller not found.
I/flutter (17377): else statement - no data retrieved
I/DynamiteModule(17377): Considering local module providerinstaller:0 and remote module providerinstaller:0
W/ProviderInstaller(17377): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
D/ConnectivityManager(17377): requestNetwork; CallingUid : 10225, CallingPid : 17377
I/flutter (17377): else statement - no data retrieved


Thanks in advance, any help will definitely be appreciated.

**Comment by lohanidamodar** [comment]
1. you are using latest version of Firestore plugin, as you are using Firebase.initializeApp(). Tip: call Firebase.initializeApp() in your main function as did in the firebase.flutter.dev documentation
2. To use latest versions of firebase ecosystem, you need to update firebase_helpers to latest version too
3. In latest version of firebase_helpers there is not .createItem() function, you should instead use `create(<Map,String>)` and directly pass the map instead of object

These changes might solve your problem.

**Comment by cavedweller** [comment]
I have called the Firebase.initializeApp() in my main function 

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();

  runApp(MainNet());
}

I am also running the latest version of the helpers package being firebase_helpers: ^0.2.0.

I have updated the code to run the new code of create

await eventDBS.create({
                            "description": _description.text,
                            "event_date": uploadDaySelected(),
                          });
It does work in adding the event to firebase

![firebase snapshot](https://user-images.githubusercontent.com/70595829/92100325-f444ed00-eddb-11ea-96c1-f115428a955a.PNG)

the output on the debug console is the same

D/ConnectivityManager( 3591): unregisterNetworkCallback; CallingUid : 10225, CallingPid : 3591
D/ConnectivityManager( 3591): unregisterNetworkCallback; CallingUid : 10225, CallingPid : 3591
W/lumic.SocialAp( 3591): Accessing hidden method Ldalvik/system/CloseGuard;->close()V (light greylist, linking)
D/ConnectivityManager( 3591): requestNetwork; CallingUid : 10225, CallingPid : 3591
W/DynamiteModule( 3591): Local module descriptor class for providerinstaller not found.
I/flutter ( 3591): else statement - no data retrieved
I/DynamiteModule( 3591): Considering local module providerinstaller:0 and remote module providerinstaller:0
W/ProviderInstaller( 3591): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
D/ConnectivityManager( 3591): requestNetwork; CallingUid : 10225, CallingPid : 3591
I/flutter ( 3591): else statement - no data retrieved

This problem has been eating away at me for weeks now, thanks for your quick responses again.

**Comment by lohanidamodar** [comment]
In VS code when you run in debug mode in debug sidebar at bottom on breakpoints tab, there is option to have breakpoint all exceptions, the data is not coming, means there might be some exception. check All Exceptions in the Breakpoints tab and see what exceptions you get

**Comment by cavedweller** [comment]
I have received an Exception stating 'NoSuchMethodError: The method 'toDate' was called on null.' this is referencing to the provider class, factory EventUpload.fromDS section.

The good news is that if i comment out eventDate: data['event_date'].toDate(), then the debug console shows that i am receiving data, so at least we know that the database is talking to the app. but then it throws errors that 'year' was called on null

**Comment by lohanidamodar** [comment]
So some of your events have event_date null, check database to remove the events with null event_date
Also  change the line `eventDate: data['event_date'].toDate(),` to `eventDate: data['event_date']?.toDate(),` just to be safe and finally
Where ever in code you are accessing event date, check if null before trying to display it.

**Comment by cavedweller** [comment]
Absolute legend, everything is working as it should be. Thank you so much for your assistance.

**Comment by lohanidamodar** [comment]
@cavedweller Great job!! Glad it helped!!
