### ISSUE TITLE
How do you add new event with time without updating the time for past events?

### ISSUE THREAD

**Issue by serpentdrake** [lohanidamodar/flutter_calendar#5]
![planner](https://user-images.githubusercontent.com/71421106/94666233-ca7dd800-033f-11eb-8f90-aec6f3326e7b.jpg)

so I was trying to implement a start time and end time for each event but then I encountered a problem where everytime I add a new task the time updates to the new task time and the time for the old tasks changes

**Comment by lohanidamodar** [comment]
That's a error in your code, show your code how you have implemented adding events then I might be able to help you.

**Comment by serpentdrake** [comment]
its the same as the tutorial but I just added the date time picker.                            
                            
![lecode](https://user-images.githubusercontent.com/71421106/94669633-16cb1700-0344-11eb-8537-b070451ee661.jpg)

**Comment by lohanidamodar** [comment]
The start time and end time has to be added to each event, you are not doing that. May be you need to learn more on the basic concepts of data management itself.

**Comment by serpentdrake** [comment]
I see, do you have any videos regarding this?  and also thanks for that wonderful tutorial man, really loved it

**Comment by lohanidamodar** [comment]
Sorry, these are basic programming concept itself. May be checkout other apps, how people have done things.
May be this might be of some help, but do search for other projects on github how others are doing
https://github.com/lohanidamodar/flutter_achiver

**Comment by serpentdrake** [comment]
thanks :D
