### ISSUE TITLE
"createItem" doesn't work now

### ISSUE THREAD

**Issue by Vasajj** [lohanidamodar/flutter_calendar#6]
in add_event.dart

await eventDBS.createItem(EventModel(
                                  title: _title.text,
                                  description: _description.text,
                                  eventDate: DateTime.now()
                                ));
shows error: 
info: 'createItem' is deprecated and shouldn't be used. Use create(Map<String,dynamic> data, {String id}) instead.. (

**Comment by lohanidamodar** [comment]
Check part3-final branch, it has the latest updated code. Also yes the asnwer is given there, createItem is deprecated and you can use create instead.
