### ISSUE TITLE
DatabaseItem is deprecated and should not be used?

### ISSUE THREAD

**Issue by JasonSleigh** [lohanidamodar/flutter_calendar#7]
I have followed your video's but found a blue error in VS code saying that 'DatabaseItem' is deprecated and shouldn't be used. Do not extend it anymore.

Does this mean that I should just leave it as...
`class EventModel {
 final String id;
...
}`

please help as I don't want to be using redundant code.

**Comment by lohanidamodar** [comment]
@JasonSleigh Yes you are correct, you no longer need to extend the DatabaseItem class. Its works without extending that.

**Comment by JasonSleigh** [comment]
So I have removed the Database item and am now getting an error at:
`super(id):` Too many positional arguments: 0 expected, but 1 found. (if I remove the super(id) I then get:
`factory EventModel(` Constructors can't return values.

What should I put in the factory's place? sorry if this is a simple fix I am fairly new to flutter.

**Comment by lohanidamodar** [comment]
Once you remove the DatabaseItem extended class, you don't need to call Super as well as there is no super class extended from
